name	'puppetmodule-motd'
version	'0.0.2'
source	'https://github.com/pcanham/puppetmodule_motd.git'
author	'pcanham'
license	''
summary	'Message Of The Day Banner'
dependency 'ripienaar/concat', '0.2.0'
description	'Simple module to maintain /etc/motd'
project_page	'https://github.com/pcanham/puppetmodule_motd.git'
