name    'puppetmodule_motd'
version '0.01'
source  'git@git-infra.internal:puppet/puppetmodule_motd.git'
author   'pcanham'
license ''
summary 'Message Of The Day Banner'
description 'Simple module to maintain /etc/issue + /etc/motd'
project_page 'http://git-infra.internal/puppet/puppetmodule_motd.git'
